# Generated by Django 4.2.5 on 2023-09-21 19:35

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('footballers', '0002_alter_country_options_alter_footballclub_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FootballerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='images')),
                ('footballer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='footballers.footballer')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'abstract': False,
            },
        ),
    ]
